### PR TITLE
Swift 4.2 branch add davez stringswitch improvements

### PR DESCRIPTION
**Pull request by gottesmm**
Some nice improvements from upstream by @davezarzycki! I am cherry-picking this since I want to use StringLiterals with StringSwitches... but evidently this also significantly speeds up string switch.

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci test and merge

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by davezarzycki** [comment]
Hi @gottesmm – I'd mark this as "reviewed" as a nod to @jrose-apple's proposal to have all changes be reviewed, but I don't think @tkremenek added me to the committer list for `swift-llvm` and `swift-clang` when he gave me commit access to a bunch of repositories. Otherwise, thanks for cherry picking this change!

**Comment by gottesmm** [comment]
@davezarzycki I am not sure if the process is any different. I would just ask @tkremenek to fix, no?

**Comment by davezarzycki** [comment]
PS – Don't forget the corresponding `clang` changes.

**Comment by gottesmm** [comment]
@davezarzycki next time you are doing stuff like this, can you state in the commit message the relevant clang change or vis-a-versa. Or at least a message saying there is a clang change.

**Comment by gottesmm** [comment]
Nm. I see you put in the reference in the clang tree. I guess I am asking to put a note in the LLVM side that there is a clang commit that goes with it.

**Comment by gottesmm** [comment]
apple/swift-clang#180

@swift-ci test

**Comment by davezarzycki** [comment]
Will do

**Comment by gottesmm** [comment]
apple/swift-clang#180

@swift-ci test

**Comment by gottesmm** [comment]
apple/swift-clang#180

@swift-ci clean test

**Comment by gottesmm** [comment]
Looks like there is some weirdness with workspace.

**Comment by gottesmm** [comment]
It is failing due to Ninja being already checked out.

**Comment by gottesmm** [comment]
apple/swift-clang#180

@swift-ci clean test

**Comment by gottesmm** [comment]
apple/swift-clang#180

@swift-ci clean test

**Comment by gottesmm** [comment]
I don't think this repo supports clean testing.

**Comment by gottesmm** [comment]
apple/swift-clang#180

@swift-ci test

**Comment by gottesmm** [comment]
@davezarzycki any thoughts on the linux failure? Is the problem that we are using a global instead of a string literal?

**Comment by davezarzycki** [comment]
Yup. I'd switch the header file to a `#define` instead of a `static const` variable. The identifier implies that it is a `#define` anyway.

**Comment by jrose-apple** [comment]
Please don't use a macro. If what's there isn't working, just don't use the same pattern for whatever you want to StringSwitch over.

**Comment by davezarzycki** [comment]
(I’m not in front of my computer)

I wonder if making the size of the global `static const` array explicit would be enough to make `llvm::StringLiteral` happy.

**Comment by jrose-apple** [comment]
No, that doesn't make a difference in C++.

**Comment by jrose-apple** [comment]
What's master-next doing so that this doesn't fail? Dave's changes have been in LLVM for a while now.

**Comment by gottesmm** [comment]
Just to satisfy my paranoia, I am going to do another test since I based the clang commit on stable when we did these tests before. There shouldn't be a difference...

**Comment by gottesmm** [comment]
apple/swift-clang#180

@swift-ci test

**Comment by gottesmm** [comment]
I am trying this on rad-main to find the problem. I also fixed up the branch so that we get the proper cherry-pick -x commits.

**Comment by gottesmm** [comment]
Found the problem. There is going to be a swift commit as well ; ).

**Pull request merged**
