### PR TITLE
radar42585636-demangling requirements

### PR DESCRIPTION
**Pull request by weliveindetail**
Cherry picks from the upstream LLVM required for https://github.com/apple/swift-lldb/pull/812

### CODE REVIEW

**Review by JDevlieghere — COMMENTED** [review]
Looks good. Did you have to resolve any conflicts?

**Review by JDevlieghere — APPROVED** [review]

**Comment by weliveindetail** [comment]
Thanks, no conflicts here only in LLDB

**Comment by JDevlieghere** [comment]
One more thing: LLDB's stable branch uses the swift-5.0-branch for LLVM. So you should cherry-pick these commits on that branch. You can create a new PR or directly push them to that branch.

**Comment by weliveindetail** [comment]
Ok good to know, you mean here? https://github.com/apple/swift-llvm/tree/swift-5.0-branch

**Comment by JDevlieghere** [comment]
Yep, that's it!

**Comment by weliveindetail** [comment]
Thks! Here we go: https://github.com/apple/swift-llvm/pull/107

**Comment by bob-wilson** [comment]
This PR should not be merged (and hopefully cannot be merged due to restricted branch permissions). The stable branch is intended to be a "branch alias" that tracks the current release branch (swift-5.0-branch). When you merge your other PR (#107), it will get automatically merged to stable.

**Comment by weliveindetail** [comment]
Oh thanks for the info. Haven't worked much with the swift-lldb repo yet.

**Pull request closed without merging**
