### PR TITLE
llvm/IR/DiagnosticHandler.h: Add include guard, or -fmodules would be…

### PR DESCRIPTION
**Pull request by adrian-prantl**
… confused.

git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@313456 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by adrian-prantl** [comment]
This fixes the build when running `build-script -- --llvm-enable-modules=true`.

**Comment by adrian-prantl** [comment]
@bob-wilson looks like I don't have the permission to merge into stable.

**Comment by adrian-prantl** [comment]
Nevermind. The next time we forward stable this will be obsolete anyway.

**Comment by bob-wilson** [comment]
Stable is locked so that it will always match the current release branch.

**Pull request closed without merging**
