### PR TITLE
[cmake] Add support for using the standalone leaks sanitizer with LLVM.

### PR DESCRIPTION
**Pull request by gottesmm**
This commit causes LLVM_USE_SANITIZER to now accept the "Leaks" option. This
will cause cmake to pass in -fsanitize=leak in all of the appropriate places.

I am making this change so that I can setup a linux bot that only detects
leaks.

git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@305839 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit 864e349715f5e32049bef560a23777b465f6c8ca)

### CODE REVIEW

**Comment by gottesmm** [comment]
@llvm-beanz Chris, can you review?

**Comment by gottesmm** [comment]
@swift-ci test

**Comment by llvm-beanz** [comment]
LGTM.

**Comment by gottesmm** [comment]
@fredriss said I didn't need to do CCC for this since it is NFC. Merging!

**Pull request merged**
