### PR TITLE
Cherry pick coverage updates

### PR DESCRIPTION
**Pull request by vedantk**

### CODE REVIEW

**Comment by vedantk** [comment]
Please test with following PR:
https://github.com/apple/swift-clang/pull/135

@swift-ci Please test macOS platform

**Comment by vedantk** [comment]
@swift-ci Please test macOS platform

**Comment by shahmishal** [comment]
Please test with following PR:
apple/swift-clang#135

@swift-ci Please test OS X platform

**Comment by vedantk** [comment]
Ah, it looks like I got the "please test" command wrong. Thanks for the clarification.

Could you cancel this build? I started a build & test with #12490.

**Comment by vedantk** [comment]
No related test failures in #12490.

**Pull request merged**
