### PR TITLE
Changes for LLDB upstream merge

### PR DESCRIPTION
**Pull request by tfiala**
The LLDB team is doing a merge from swift-lldb/master-next into swift-lldb/master to go along with the llvm and clang swift-3.1-branch branch.  This PR is a small collection of changes where code was either refactored out of LLDB into LLVM, or was added to support LLDB use cases, and are easier to bring in than to temporarily mask out of the LLDB merge.

I will be using the PR for cross-repo merge testing.

### CODE REVIEW

**Comment by tfiala** [comment]
Most of these changes are around llvm::StringRef.

**Comment by tfiala** [comment]
@fredriss, these are the cherry-picks I was referring to that I want to pull into the swift-3.1-branch branch of LLVM.  The latest pull of upstream LLDB into the swift-lldb/master branch, which is in sync with the swift-3.1-branch of LLVM, makes heavy use of these.  My options were to undo those changes in LLDB, or cherry-pick the small-ish set of underlying changes.  I went for the latter, since that was the longer term right solution IMHO.

**Comment by fredriss** [comment]
@swift-ci please test

**Comment by fredriss** [comment]
@tfiala Do you think the test failures could be due to your cherry-picks?

**Comment by tfiala** [comment]
@fredriss having a look...

**Comment by tfiala** [comment]
Fast tracking this.  I (mistakenly) committed the lldb side and forgot I needed this in.  I'm going to see if the error shows up on a retest.

@swift-ci Please test OS X platform

**Comment by tfiala** [comment]
I reverted the merge in lldb that was depending on this a little while back.

I'm running the tests locally and seeing if one of these changes in llvm are causing the Swift failure.  I also kicked off the macOS side again, just for another data point.

**Comment by tfiala** [comment]
I'm running the Swift test suite with this commit, and I'm not getting any failures.  However, my test run is only picking up 3021 tests, not the 8000+ that I see in the output here:

```
Testing Time: 689.73s
  Expected Passes    : 2945
  Expected Failures  : 8
  Unsupported Tests  : 68
-- check-swift-macosx-x86_64 finished --
--- Finished tests for swift ---
```

So I may be missing the failing test case via another needed repo.

I'm now waiting on the macOS builder here to see what happens on the second run.

**Comment by tfiala** [comment]
Ah okay I looked into the failure a little deeper - it was specifically on the iPhone simulator.  And the issue was what appeared to be a simulator error, not a test failure:

```
/Users/buildnode/jenkins/workspace/swift-llvm-PR-osx/swift/validation-test/Reflection/reflect_Int32.swift:32:14: error: expected string not found in input
// CHECK-32: Reflecting an object.
             ^
<stdin>:1:1: note: scanning from here
2016-11-01 16:17:48.888 simctl[69358:213162] CoreSimulatorService connection interrupted. Resubscribing to notifications.
^
<stdin>:1:67: note: possible intended match here
2016-11-01 16:17:48.888 simctl[69358:213162] CoreSimulatorService connection interrupted. Resubscribing to notifications.
                                                                  ^
```

**Comment by tfiala** [comment]
The failed Swift simulator test is flaky due to a simulator failure.

Merging as the second macOS run on CI worked fine.

**Pull request merged**
