### PR TITLE
[SLPVectorizer] Debug info shouldn't impact spill cost computation.

### PR DESCRIPTION
**Pull request by dcci**
<rdar://problem/39794738>

(Also, PR32761).

Differential Revision:  https://reviews.llvm.org/D46199

git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@331199 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by dcci** [comment]
@swift-ci test and merge

**Comment by dcci** [comment]
@bob-wilson do we have CI on this branch or I can just go ahead and merge?

**Comment by bob-wilson** [comment]
Sorry for the slow response. I don't know why the pull request testing didn't work, but it isn't mandatory for this repo and your change looks good.

**Comment by dcci** [comment]
Fair enough. Thank you @bob-wilson !

**Pull request merged**
