### PR TITLE
Cherry-pick "[llvm] [cmake] Provide split include paths in LLVMConfig" from llvm.org/master

### PR DESCRIPTION
**Pull request by bulbazord**
I'd like to cherry-pick this so that I can cherry-pick some accompanying changes to swift-lldb's build.

cc @compnerd @weliveindetail

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @dexonsmith @bob-wilson @adrian-prantl

**Comment by adrian-prantl** [comment]
This has been on trunk for two months, so I assume this is safe.

**Comment by adrian-prantl** [comment]
@swift-ci test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by weliveindetail** [comment]
We have https://reviews.llvm.org/D57995 on the LLDB side?
Hope it's going to work with swift.
Otherwise, yes that should be fine.

**Comment by bulbazord** [comment]
@weliveindetail: It's not in swift-lldb yet, I intend to cherry-pick that patch to swift-lldb after this patch goes in.

**Comment by compnerd** [comment]
Seems that everyone is okay with this, lets merge this and get the LLDB side sorted out.

**Pull request merged**
