### PR TITLE
Update stable branch from apple/stable/20190619 branch 

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by davezarzycki** [comment]
This broke my Linux box (Fedora 31 – x86_64). Was this expected? How can I help debug this?

```
FAIL: LLVM :: tools/llvm-readobj/elf-loadname.test (31647 of 32022)
******************** TEST 'LLVM :: tools/llvm-readobj/elf-loadname.test' FAILED ********************
Script:
--
: 'RUN: at line 3';   /home/dave/b/u/t/bin/yaml2obj /home/dave/s/u/llvm/test/tools/llvm-readobj/elf-loadname.test -o /home/dave/b/u/t/test/tools/llvm-readobj/Output/elf-loadname.test.tmp.o
: 'RUN: at line 4';   /home/dave/b/u/t/bin/llvm-readobj /home/dave/b/u/t/test/tools/llvm-readobj/Output/elf-loadname.test.tmp.o | /home/dave/b/u/t/bin/FileCheck /home/dave/s/u/llvm/test/tools/llvm-readobj/elf-loadname.test --check-prefix LLVM
: 'RUN: at line 5';   /home/dave/b/u/t/bin/llvm-readelf --dynamic-table /home/dave/b/u/t/test/tools/llvm-readobj/Output/elf-loadname.test.tmp.o | /home/dave/b/u/t/bin/FileCheck /home/dave/s/u/llvm/test/tools/llvm-readobj/elf-loadname.test --check-prefix GNU
--
Exit Code: 1

Command Output (stderr):
--
/home/dave/s/u/llvm/test/tools/llvm-readobj/elf-loadname.test:10:14: error: LLVM-NEXT: expected string not found in input
# LLVM-NEXT: LoadName: test.so
             ^
<stdin>:6:1: note: scanning from here
LoadName: <Not found>
^

--

********************
Testing Time: 30.88s
********************
Failing Tests (2):
    LLVM-Unit :: TextAPI/./TextAPITests/TBDv3.WriteFile
    LLVM :: tools/llvm-readobj/elf-loadname.test

  Expected Passes    : 23789
  Expected Failures  : 65
  Unsupported Tests  : 8166
  Unexpected Failures: 2
```

**Comment by davezarzycki** [comment]
After some bisection, the two failing tests are caused by the following two commits:

3355eab4baeeefb90b91270e269fb630a46aaeb0
76e86d91f21e768543e0f65f8d3f6ef39f7f6651

For whatever it may be worth, top-of-tree LLVM builds/tests clean on my machine.

**Comment by shahmishal** [comment]
@cyndyishida @JDevlieghere Do you know why @davezarzycki is seeing these failures? Do you know if we can cherry-pick a fix on to `apple/stable/20190619`?

**Comment by JDevlieghere** [comment]
It's possible that I missed a cherry pick for George's ELF changes that only affects Fedora. I'll go over the commits tomorrow and see if anything stands out. Maybe it's just a matter of cherry-picking some of the more recent changes.I only went as far as was needed for LLDB to build and pass the tests.

**Comment by davezarzycki** [comment]
@JDevlieghere – I didn't see any more recent ELF changes that looked obvious, but I wasn't looking that hard. For whatever it may be worth, I didn't see any evidence that 76e86d91f21e768543e0f65f8d3f6ef39f7f6651 broke the LLVM build bots (i.e. no "quick fix" commit shortly thereafter), so that implies to me that a dependent commit was overlooked.

**Comment by cyndyishida** [comment]
@davezarzycki Would you happen to know what expectation failed for
`LLVM-Unit :: TextAPI/./TextAPITests/TBDv3.WriteFile`?

**Comment by cyndyishida** [comment]
The failure for `LLVM-Unit :: TextAPI/./TextAPITests/TBDv3.WriteFile` is because of missing whitespace in a string comparison. The whitespace also doesn't appear upstream so no patch exists, and like you said, the tests pass there. I'm looking into the cleanest fix for this.

**Comment by davezarzycki** [comment]
```
FAIL: LLVM-Unit :: TextAPI/./TextAPITests/TBDv3.WriteFile (3543 of 32022)
******************** TEST 'LLVM-Unit :: TextAPI/./TextAPITests/TBDv3.WriteFile' FAILED ********************
Note: Google Test filter = TBDv3.WriteFile
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TBDv3
[ RUN      ] TBDv3.WriteFile
/home/dave/s/u/llvm/unittests/TextAPI/TextStubV3Tests.cpp:180: Failure
      Expected: tbd_v3_file3
      Which is: "--- !tapi-tbd-v3\narchs:           [ i386, x86_64 ]\nplatform:        macosx\ninstall-name:    '/usr/lib/libfoo.dylib'\ncurrent-version: 1.2.3\ncompatibility-version: 0\nswift-abi-version: 5\nexports:\n  - archs:           [ i386 ]\n    symbols:         [ _sym1 ]\n    weak-def-symbols: [ _sym2 ]\n    thread-local-symbols: [ _sym3 ]\n  - archs:           [ x86_64 ]\n    allowable-clients: [ clientA ]\n    re-exports:      [ '/usr/lib/libfoo.dylib' ]\n    objc-classes:    [ Class1 ]\n    objc-eh-types:   [ Class1 ]\n    objc-ivars:      [ Class1._ivar1 ]\n...\n"
To be equal to: Buffer.c_str()
      Which is: "--- !tapi-tbd-v3\narchs:           [ i386, x86_64 ]\nplatform:        macosx\ninstall-name:    '/usr/lib/libfoo.dylib'\ncurrent-version: 1.2.3\ncompatibility-version: 0\nswift-abi-version: 5\nexports:         \n  - archs:           [ i386 ]\n    symbols:         [ _sym1 ]\n    weak-def-symbols: [ _sym2 ]\n    thread-local-symbols: [ _sym3 ]\n  - archs:           [ x86_64 ]\n    allowable-clients: [ clientA ]\n    re-exports:      [ '/usr/lib/libfoo.dylib' ]\n    objc-classes:    [ Class1 ]\n    objc-eh-types:   [ Class1 ]\n    objc-ivars:      [ Class1._ivar1 ]\n...\n"
With diff:
@@ -6,5 +6,5 @@
 compatibility-version: 0
 swift-abi-version: 5
-exports:
+exports:         
   - archs:           [ i386 ]
     symbols:         [ _sym1 ]

[  FAILED  ] TBDv3.WriteFile (0 ms)
[----------] 1 test from TBDv3 (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TBDv3.WriteFile

 1 FAILED TEST

```

**Comment by cyndyishida** [comment]
That test should pass now. I cherry-picked https://github.com/apple/swift-llvm/commit/6553e238d1466ab5524144d8d7fd1b5e35fa4099 onto `apple/stable/20190619`. Sorry about that!

**Comment by davezarzycki** [comment]
@cyndyishida – Thanks again for the quick fix. Did you run the clang tests? As it turns out, 6553e238d1466ab5524144d8d7fd1b5e35fa4099 breaks four clang unit tests:

```
FAIL: Clang-Unit :: Tooling/./ToolingTests/AtomicChangeTest.AtomicChangeToYAML (15007 of 15438)
******************** TEST 'Clang-Unit :: Tooling/./ToolingTests/AtomicChangeTest.AtomicChangeToYAML' FAILED ********************
Note: Google Test filter = AtomicChangeTest.AtomicChangeToYAML
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from AtomicChangeTest
[ RUN      ] AtomicChangeTest.AtomicChangeToYAML
/home/dave/s/u/clang/unittests/Tooling/RefactoringTest.cpp:1189: Failure
      Expected: "---\n" "Key:             'input.cpp:20'\n" "FilePath:        input.cpp\n" "Error:           ''\n" "InsertedHeaders: \n" "  - a.h\n" "RemovedHeaders:  \n" "  - b.h\n" "Replacements:    \n" "  - FilePath:        input.cpp\n" "    Offset:          20\n" "    Length:          0\n" "    ReplacementText: aa\n" "  - FilePath:        input.cpp\n" "    Offset:          30\n" "    Length:          0\n" "    ReplacementText: bb\n" "...\n"
      Which is: "---\nKey:             'input.cpp:20'\nFilePath:        input.cpp\nError:           ''\nInsertedHeaders: \n  - a.h\nRemovedHeaders:  \n  - b.h\nReplacements:    \n  - FilePath:        input.cpp\n    Offset:          20\n    Length:          0\n    ReplacementText: aa\n  - FilePath:        input.cpp\n    Offset:          30\n    Length:          0\n    ReplacementText: bb\n...\n"
To be equal to: YAMLString.c_str()
      Which is: "---\nKey:             'input.cpp:20'\nFilePath:        input.cpp\nError:           ''\nInsertedHeaders:\n  - a.h\nRemovedHeaders:\n  - b.h\nReplacements:\n  - FilePath:        input.cpp\n    Offset:          20\n    Length:          0\n    ReplacementText: aa\n  - FilePath:        input.cpp\n    Offset:          30\n    Length:          0\n    ReplacementText: bb\n...\n"
With diff:
@@ -3,9 +3,9 @@
 FilePath:        input.cpp
 Error:           ''
-InsertedHeaders: 
+InsertedHeaders:
   - a.h
-RemovedHeaders:  
+RemovedHeaders:
   - b.h
-Replacements:    
+Replacements:
   - FilePath:        input.cpp
     Offset:          20

[  FAILED  ] AtomicChangeTest.AtomicChangeToYAML (1 ms)
[----------] 1 test from AtomicChangeTest (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AtomicChangeTest.AtomicChangeToYAML

 1 FAILED TEST

********************
FAIL: Clang-Unit :: Tooling/./ToolingTests/DiagnosticsYamlTest.serializesDiagnostics (15071 of 15438)
******************** TEST 'Clang-Unit :: Tooling/./ToolingTests/DiagnosticsYamlTest.serializesDiagnostics' FAILED ********************
Note: Google Test filter = DiagnosticsYamlTest.serializesDiagnostics
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DiagnosticsYamlTest
[ RUN      ] DiagnosticsYamlTest.serializesDiagnostics
/home/dave/s/u/clang/unittests/Tooling/DiagnosticsYamlTest.cpp:112: Failure
      Expected: YAMLContent
      Which is: "---\nMainSourceFile:  'path/to/source.cpp'\nDiagnostics:     \n  - DiagnosticName:  'diagnostic#1'\n    DiagnosticMessage: \n      Message:         'message #1'\n      FilePath:        'path/to/source.cpp'\n      FileOffset:      55\n      Replacements:    \n        - FilePath:        'path/to/source.cpp'\n          Offset:          100\n          Length:          12\n          ReplacementText: 'replacement #1'\n  - DiagnosticName:  'diagnostic#2'\n    DiagnosticMessage: \n      Message:         'message #2'\n      FilePath:        'path/to/header.h'\n      FileOffset:      60\n      Replacements:    \n        - FilePath:        'path/to/header.h'\n          Offset:          62\n          Length:          2\n          ReplacementText: 'replacement #2'\n  - DiagnosticName:  'diagnostic#3'\n    DiagnosticMessage: \n      Message:         'message #3'\n      FilePath:        'path/to/source2.cpp'\n      FileOffset:      72\n      Replacements:    []\n    Notes:           \n      - Message:         Note1\n        FilePath:        'path/to/note1.cpp'\n        FileOffset:      88\n        Replacements:    []\n      - Message:         Note2\n        FilePath:        'path/to/note2.cpp'\n        FileOffset:      99\n        Replacements:    []\n...\n"
To be equal to: YamlContentStream.str()
      Which is: "---\nMainSourceFile:  'path/to/source.cpp'\nDiagnostics:\n  - DiagnosticName:  'diagnostic#1'\n    DiagnosticMessage:\n      Message:         'message #1'\n      FilePath:        'path/to/source.cpp'\n      FileOffset:      55\n      Replacements:\n        - FilePath:        'path/to/source.cpp'\n          Offset:          100\n          Length:          12\n          ReplacementText: 'replacement #1'\n  - DiagnosticName:  'diagnostic#2'\n    DiagnosticMessage:\n      Message:         'message #2'\n      FilePath:        'path/to/header.h'\n      FileOffset:      60\n      Replacements:\n        - FilePath:        'path/to/header.h'\n          Offset:          62\n          Length:          2\n          ReplacementText: 'replacement #2'\n  - DiagnosticName:  'diagnostic#3'\n    DiagnosticMessage:\n      Message:         'message #3'\n      FilePath:        'path/to/source2.cpp'\n      FileOffset:      72\n      Replacements:    []\n    Notes:\n      - Message:         Note1\n        FilePath:        'path/to/note1.cpp'\n        FileOffset:      88\n        Replacements:    []\n      - Message:         Note2\n        FilePath:        'path/to/note2.cpp'\n        FileOffset:      99\n        Replacements:    []\n...\n"
With diff:
@@ -1,11 +1,11 @@
 ---
 MainSourceFile:  'path/to/source.cpp'
-Diagnostics:     
+Diagnostics:
   - DiagnosticName:  'diagnostic#1'
-    DiagnosticMessage: 
+    DiagnosticMessage:
       Message:         'message #1'
       FilePath:        'path/to/source.cpp'
       FileOffset:      55
-      Replacements:    
+      Replacements:
         - FilePath:        'path/to/source.cpp'
           Offset:          100
@@ -13,9 +13,9 @@
           ReplacementText: 'replacement #1'
   - DiagnosticName:  'diagnostic#2'
-    DiagnosticMessage: 
+    DiagnosticMessage:
       Message:         'message #2'
       FilePath:        'path/to/header.h'
       FileOffset:      60
-      Replacements:    
+      Replacements:
         - FilePath:        'path/to/header.h'
           Offset:          62
@@ -23,5 +23,5 @@
           ReplacementText: 'replacement #2'
   - DiagnosticName:  'diagnostic#3'
-    DiagnosticMessage: 
+    DiagnosticMessage:
       Message:         'message #3'
       FilePath:        'path/to/source2.cpp'
@@ -28,5 +28,5 @@
       FileOffset:      72
       Replacements:    []
-    Notes:           
+    Notes:
       - Message:         Note1
         FilePath:        'path/to/note1.cpp'

[  FAILED  ] DiagnosticsYamlTest.serializesDiagnostics (0 ms)
[----------] 1 test from DiagnosticsYamlTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DiagnosticsYamlTest.serializesDiagnostics

 1 FAILED TEST

********************
FAIL: Clang-Unit :: Tooling/./ToolingTests/RefactoringActionRulesTest.MyFirstRefactoringRule (15239 of 15438)
******************** TEST 'Clang-Unit :: Tooling/./ToolingTests/RefactoringActionRulesTest.MyFirstRefactoringRule' FAILED ********************
Note: Google Test filter = RefactoringActionRulesTest.MyFirstRefactoringRule
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from RefactoringActionRulesTest
[ RUN      ] RefactoringActionRulesTest.MyFirstRefactoringRule
/home/dave/s/u/clang/unittests/Tooling/RefactoringActionRulesTest.cpp:127: Failure
      Expected: "---\n" "Key:             'input.cpp:30'\n" "FilePath:        input.cpp\n" "Error:           ''\n" "InsertedHeaders: []\n" "RemovedHeaders:  []\n" "Replacements:    \n" "  - FilePath:        input.cpp\n" "    Offset:          30\n" "    Length:          1\n" "    ReplacementText: b\n" "...\n"
      Which is: "---\nKey:             'input.cpp:30'\nFilePath:        input.cpp\nError:           ''\nInsertedHeaders: []\nRemovedHeaders:  []\nReplacements:    \n  - FilePath:        input.cpp\n    Offset:          30\n    Length:          1\n    ReplacementText: b\n...\n"
To be equal to: YAMLString.c_str()
      Which is: "---\nKey:             'input.cpp:30'\nFilePath:        input.cpp\nError:           ''\nInsertedHeaders: []\nRemovedHeaders:  []\nReplacements:\n  - FilePath:        input.cpp\n    Offset:          30\n    Length:          1\n    ReplacementText: b\n...\n"
With diff:
@@ -5,5 +5,5 @@
 InsertedHeaders: []
 RemovedHeaders:  []
-Replacements:    
+Replacements:
   - FilePath:        input.cpp
     Offset:          30

[  FAILED  ] RefactoringActionRulesTest.MyFirstRefactoringRule (0 ms)
[----------] 1 test from RefactoringActionRulesTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RefactoringActionRulesTest.MyFirstRefactoringRule

 1 FAILED TEST

********************
FAIL: Clang-Unit :: Tooling/./ToolingTests/ReplacementsYamlTest.serializesReplacements (15310 of 15438)
******************** TEST 'Clang-Unit :: Tooling/./ToolingTests/ReplacementsYamlTest.serializesReplacements' FAILED ********************
Note: Google Test filter = ReplacementsYamlTest.serializesReplacements
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ReplacementsYamlTest
[ RUN      ] ReplacementsYamlTest.serializesReplacements
/home/dave/s/u/clang/unittests/Tooling/ReplacementsYamlTest.cpp:46: Failure
      Expected: "---\n" "MainSourceFile:  '/path/to/source.cpp'\n" "Replacements:    \n" "  - FilePath:        '/path/to/file1.h'\n" "    Offset:          232\n" "    Length:          56\n" "    ReplacementText: 'replacement #1'\n" "  - FilePath:        '/path/to/file2.h'\n" "    Offset:          301\n" "    Length:          2\n" "    ReplacementText: 'replacement #2'\n" "...\n"
      Which is: "---\nMainSourceFile:  '/path/to/source.cpp'\nReplacements:    \n  - FilePath:        '/path/to/file1.h'\n    Offset:          232\n    Length:          56\n    ReplacementText: 'replacement #1'\n  - FilePath:        '/path/to/file2.h'\n    Offset:          301\n    Length:          2\n    ReplacementText: 'replacement #2'\n...\n"
To be equal to: YamlContentStream.str().c_str()
      Which is: "---\nMainSourceFile:  '/path/to/source.cpp'\nReplacements:\n  - FilePath:        '/path/to/file1.h'\n    Offset:          232\n    Length:          56\n    ReplacementText: 'replacement #1'\n  - FilePath:        '/path/to/file2.h'\n    Offset:          301\n    Length:          2\n    ReplacementText: 'replacement #2'\n...\n"
With diff:
@@ -1,5 +1,5 @@
 ---
 MainSourceFile:  '/path/to/source.cpp'
-Replacements:    
+Replacements:
   - FilePath:        '/path/to/file1.h'
     Offset:          232

[  FAILED  ] ReplacementsYamlTest.serializesReplacements (0 ms)
[----------] 1 test from ReplacementsYamlTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ReplacementsYamlTest.serializesReplacements

 1 FAILED TEST

********************
Testing Time: 31.90s
********************
Failing Tests (4):
    Clang-Unit :: Tooling/./ToolingTests/AtomicChangeTest.AtomicChangeToYAML
    Clang-Unit :: Tooling/./ToolingTests/DiagnosticsYamlTest.serializesDiagnostics
    Clang-Unit :: Tooling/./ToolingTests/RefactoringActionRulesTest.MyFirstRefactoringRule
    Clang-Unit :: Tooling/./ToolingTests/ReplacementsYamlTest.serializesReplacements

  Expected Passes    : 15155
  Expected Failures  : 27
  Unsupported Tests  : 252
  Unexpected Failures: 4
```

**Pull request merged**
