### PR TITLE
RecordLayout.h: avoid spurious copies of values to be emitted

### PR DESCRIPTION
**Pull request by jrose-apple**
This was causing significant slowdowns for Swift AST serialization.
Oops.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

**Comment by jrose-apple** [comment]
Hm. Maybe this?

@swift-ci Please test

**Comment by jrose-apple** [comment]
@swift-ci Please test macOS

**Comment by hyp** [comment]
Shouldn't this be committed to LLVM org?

**Comment by jrose-apple** [comment]
I don't think we've upstreamed RecordLayout.h. The clients are API notes and Swift's serialization mechanism.

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Review by DougGregor — APPROVED** [review]

**Comment by jrose-apple** [comment]
apple/swift#19167
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
apple/swift#19167
@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
apple/swift#19167
@swift-ci Please test

**Comment by jrose-apple** [comment]
I'm giving up and just merging these.

**Pull request merged**
