### PR TITLE
[SystemZ] Support LRVH and STRVH opcodes

### PR DESCRIPTION
**Pull request by bryanpkc**
Summary: On Linux, /usr/include/bits/byteswap-16.h defines __byteswap_16(x) as an inlined LRVH (Load Reversed Half-word) instruction. The SystemZ back-end did not support this opcode and the inlined assembly would cause a fatal error.

Reviewers: bryanpkc, uweigand

Subscribers: llvm-commits

Differential Revision: http://reviews.llvm.org/D18732

git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@269688 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by bryanpkc** [comment]
@fredriss, could I tag you for this pull request? Thanks.

**Comment by fredriss** [comment]
@swift-ci Please test

**Comment by bryanpkc** [comment]
@fredriss The test failures do not seem related to this backend change.

**Comment by fredriss** [comment]
Yep, let's try it once more.

**Comment by fredriss** [comment]
@swift-ci please test

**Comment by bryanpkc** [comment]
@fredriss Shall we try again or can the code be merged? The x86_64 Linux and OS X test builds won't be affected by the SystemZ backend change anyway.

**Comment by fredriss** [comment]
I'm trying one last time now that the CI seems to be doing better.
@swift-ci please test

**Comment by fredriss** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
The CI system's seeing a merge conflict, even though GitHub's interface isn't showing it. Mind rebasing?

**Comment by jrose-apple** [comment]
(Sorry for the delay. It's been busy over here.)

**Comment by fredriss** [comment]
@jrose-apple The patch doesn't touch the files where there's a conflict. This is an LLVM patch the conflict is in swift...

**Comment by jrose-apple** [comment]
Huh, you're right. I misread it. Very strange.

@swift-ci Please test OS X platform

**Comment by bryanpkc** [comment]
Could we just merge? That would help the builds on s390x...

**Comment by jrose-apple** [comment]
That's up to Fred, but I personally think it makes sense. As you say, all of these files are in the SystemZ backend and cannot possibly affect the other backends.

**Comment by fredriss** [comment]
Just did that. Sorry for the delay.

**Pull request merged**
