### PR TITLE
Change llvm call once check for PowerPC(ppc64le)

### PR DESCRIPTION
**Pull request by sarveshtamba**
Change llvm call once check for PowerPC(ppc64le)

### CODE REVIEW

**Comment by bob-wilson** [comment]
You should start by getting this change (or whatever alternative is acceptable to the LLVM community) into the upstream LLVM project. Once that is done, we can cherry-pick the change to the current swift-llvm release branch. The "stable" branch here is read-only and should not be modified directly.

**Comment by sarveshtamba** [comment]
@bob-wilson - I have created a new PR - https://github.com/llvm-mirror/llvm/pull/65
Please let me know in case this is not the correct repo or in case of any other issues.

**Comment by bob-wilson** [comment]
The LLVM project does not (yet) do development on GitHub. Instructions for contributing a patch are here: http://www.llvm.org/docs/Contributing.html

**Comment by sarveshtamba** [comment]
Hi @bob-wilson ,
This change is required to resolve the call_once related errors seen while building the Swift toolchain on PowerPC64LE.
I have submitted the change in PR #129 to swift-llvm(upstream-with-swift branch).

As for submitting a patch at https://bugs.llvm.org, I have sent an e-mail request to bugs-admin@lists.llvm.org for an account creation. On getting the account, I will submit the patch immediately.

Let me know if anything else is needed from my end.

**Comment by sarveshtamba** [comment]
@bob-wilson Bug [39912 ](https://bugs.llvm.org/show_bug.cgi?id=39912)has been successfully created.
Please review and let me know.

**Pull request closed without merging**
