### PR TITLE
Rdar27110616

### PR DESCRIPTION
**Pull request by gottesmm**

### CODE REVIEW

**Comment by llvm-beanz** [comment]
LGTM.

**Comment by gottesmm** [comment]
@swift-ci Please test

**Comment by gottesmm** [comment]
It looks like the failures here are related to lldb. Once this is merged, I will follow up with them and fix this issue.

**Comment by gottesmm** [comment]
Actually, there is an additional compiler-rt failures. All of these are related to 3978820. That is not necessary for this (I just thought it would clean some things up).

I am going to push to the branch without that commit.

**Comment by gottesmm** [comment]
@swift-ci Please test

**Pull request merged**
